project:
  type: website
  output-dir: ../docs/cn
  
resources:
  - CNAME

website:
  # title: "Guillem Maya"
  # description: "A data economics blog and portfolio by Guillem Maya"
  site-url: https://guillemmaya.com
  repo-url: https://github.com/guillemmaya92/guillemmaya.com
  favicon: files/favicon.png
  back-to-top-navigation: true
  google-analytics:
    tracking-id: "G-GJVKVH4E2Y"
    anonymize-ip: true
  navbar:
    style: "docked"
    collapse: true
    background: transparent
    right:
      - href: index.qmd
        text: é¦–é¡µ
      - href: posts.qmd
        text: å¸–å­
      - href: cv.qmd
        text: ç®€å†
      - text: è¯­è¨€
        menu:
          - text: '<img src="/files/en.svg" width="16"/> è‹±æ–‡'
            href: "../{{< meta filename >}}.html"
          - text: '<img src="/files/es.svg" width="16"/> è¥¿ç­ç‰™è¯­'
            href: "../es/{{< meta filename >}}.html"
          - text: '<img src="/files/cn.svg" width="16"/> ä¸­æ–‡'
            href: "{{< meta filename >}}.html"
        
  page-footer:
    border: false
    left: |
      ä½¿ç”¨ [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    right: |
      åœ¨<a href="https://map.baidu.com/search/%E8%B5%AB%E7%BD%97%E7%BA%B3/@313782.98,5129255.33,8z" target="_blank" style="text-decoration: none; color: inherit;">èµ«ç½—çº³</a>ç”¨ <span style="color: #22bc9c;">{{< fa heart title="a heart" >}}</span> åˆ¶ä½œ

format:
  html:
    theme:
      light: [flatly, "styles/theme-light.scss"]
      dark: [darkly, "styles/theme-dark.scss"]
    css:
      - styles/styles.css
    mainfont: "Open Sans"
    fontsize: 11pt
    date-format: medium
    toc: false

bluesky-comments:
  mute-patterns:
    - "ğŸ“Œ"
    - "ğŸ”¥"
    - "/\\bspam\\b/i"  # regex pattern
  mute-users:
    - "did:plc:1234abcd"
  filter-empty-replies: true
  visible-comments: 3
  visible-subcomments: 3

editor: visual

lang: "zh"

